/**
 * Session & turn records — the RUNTIME-generated research dataset. Written live
 * by the realtime service into Payload's `sessions` collection; read-only in
 * the admin. Structured turns only — never audio (GDPR).
 */

import type { FaceEmotion } from "./emotion.js";
import type { PersonaKey } from "./persona.js";
import type { CabinControlId } from "./cabin.js";
import type { Locale } from "./telemetry.js";

export type Modality = "voice" | "text" | "tap";

/** How a card is answered: by the model (tap → user turn) or by the hub
 *  itself (instant, no LLM round — themes, voices, scales, the wizard). */
export type SeatCardKind = "confirm" | "list" | "themes" | "voices" | "scale";
export type SeatCardIcon = "check" | "x" | "minus" | "plus" | "skip" | "done";

export interface SeatCardOption {
  /** What gets sent back (a label for model cards, a setting value for local ones). */
  value: string;
  label: string;
  /** Icon-only chips (✓ ✗ − +) — the label becomes the aria-label. */
  icon?: SeatCardIcon;
}

export interface SeatCardScale {
  setting: "volume" | "speechRate" | "textSize";
  min: number;
  max: number;
  step: number;
  value: number;
  /** slider = continuous (volume, tempo); stepper = −/+ (text size). */
  control: "slider" | "stepper";
}

/**
 * A card CoSiMo shows IN THE SLIT: the spoken question as context on the
 * left, tappable actions on the right. Always paired with the SPOKEN
 * question — voice stays the primary channel. `local` cards are answered by
 * the hub (`card:answer`), model cards send the chosen label as the rider's
 * next message. One card per seat; a new turn, a tap, or `ttlMs` clears it.
 */
export interface SeatCard {
  id: string;
  kind: SeatCardKind;
  question: string;
  options: SeatCardOption[];
  local: boolean;
  scale?: SeatCardScale;
  /** Wizard progress ("2/5") when the card is one step of the customizer. */
  step?: { index: number; total: number };
  ttlMs: number;
}
export type TurnRole = "user" | "cosimo";
export type TurnOutcome =
  | "ok"
  | "not_understood"
  | "error"
  | "offline_canned"
  /** The rider barged in (talk button / new input) and the turn was aborted. */
  | "interrupted";

export interface TurnAction {
  /** Which tool CoSiMo invoked, if any (e.g. "set_light"). */
  tool: string;
  /** Target control, when the action was a cabin control. */
  control?: CabinControlId;
  /** Serialized arguments, for later analysis. */
  args?: Record<string, unknown>;
  /** What the tool returned to the model (truncated), and whether it worked. */
  result?: string;
  ok?: boolean;
  durationMs?: number;
}

export interface Turn {
  role: TurnRole;
  modality: Modality;
  lang: Locale;
  /** What was said/typed or spoken back. No audio is stored. */
  transcript: string;
  /** Classified intent for the user turn (e.g. "ask_eta", "command_light"). */
  detectedIntent?: string;
  /** @deprecated Last action only — kept for old rows. Use `actions`. */
  action?: TurnAction;
  /** Every tool call of a cosimo turn, in order (incl. set_emotion). */
  actions?: TurnAction[];
  /** The brain that answered (absent for canned turns). */
  llm?: { provider: string; model: string };
  /** Where the latency went. */
  timings?: { sttMs?: number; llmMs?: number; ttsMs?: number };
  /** The error message when outcome is "error". */
  error?: string;
  /** Face emotion CoSiMo displayed during this turn. */
  faceEmotion?: FaceEmotion;
  /** End-to-end latency for a cosimo turn, in milliseconds. */
  latencyMs?: number;
  outcome?: TurnOutcome;
  /** ISO timestamp; stamped by the realtime service. */
  at: string;
}

export interface SessionRecord {
  /** Stable session id (generated by realtime). */
  sessionId: string;
  /** Which iPad/device this conversation happened on. */
  deviceId: string;
  persona: PersonaKey;
  /** Whether the visitor consented to recording (gates persistence detail). */
  consent: boolean;
  startedAt: string;
  endedAt?: string;
  turns: Turn[];
}
